# Default values for workforce-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Labels to match to monitor against
# eg:  app.kubernetes.io/name: workforce-fg
fgMonitor:
  matchLabels:
    app.kubernetes.io/name: workforce-fg
  namespace: workforce

bgMonitor:
  port: 9191
  path: "/"
  matchLabels:
    app.kubernetes.io/name: workforce-bg
  namespace: workforce