apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configcat-proxy.fullname" . }}
  labels:
    {{- include "configcat-proxy.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ squote $value }}
  {{- end }}
  CONFIGCAT_SDKS: {{ merge .Values.CONFIGCAT_SDK_KEYS dict | toJson | squote}}
