apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "configcat-proxy.fullname" . }}
  labels:
    {{- include "configcat-proxy.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "configcat-proxy.selectorLabels" . | nindent 6 }}