apiVersion: v1
kind: Service
metadata:
  name: {{ include "configcat-proxy.fullname" . }}
  labels:
    {{- include "configcat-proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "configcat-proxy.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
