# This template is copied into pre-upgrade-secrets.yml and secrets.yml
# We do this so that our pre-upgrade scripts are properly configured before they are run.
{{ define "_base_secrets.data" }}
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ quote $val }}
  {{- end }}
{{ end }}
