
{{- if .Values.containers.bg.command -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptick-django.fullname" . }}-bg
  labels:
    {{- include "uptick-django.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "uptick-django.selectorLabelsBg" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uptick-django.selectorLabelsBg" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "uptick-django.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.containers.bg.initCommand }}
      initContainers:
        - name: {{ .Release.Name }}-init
          image: "{{ .Values.image }}"
          command: {{ .Values.containers.bg.initCommand }}
          envFrom:
          - configMapRef:
              name: {{ include "uptick-django.fullname" . }}-environment
          - secretRef:
              name: {{ include "uptick-django.fullname" . }}-secrets
      {{- end }}
      containers:
        # We use ReleaseName as papertrail logs are grouped around container names
        - name: {{ .Release.Name }}-bg
          command: {{ .Values.containers.bg.command}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.containers.bg.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "uptick-django.fullname" . }}-environment
          - secretRef:
              name: {{ include "uptick-django.fullname" . }}-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}