apiVersion: v1
kind: Secret
metadata:
  # Different name to regluar configmap. These should be deleted after installation
  name: {{ include "uptick-django.fullname" . }}-secrets-migration
  labels:
    {{- include "uptick-django.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10" # Lower weight than job. These need to be installed first
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
type: Opaque
data:
  {{- template "_base_secrets.data" . }}