apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-secrets
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val}}
  {{- end }}